# -*- coding: utf-8 -*-
"""Day30_Submission.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AjXC2Zdn3qywsuYsASgxG7l_nPZTeR0C

## Data Loading & Exploration
"""

import pandas as pd
df = pd.read_csv('/content/suv_data.csv')

"""
●	Load dataset using Pandas

●	Display first 5 rows, shape, and column names

●	Check data types and missing values
"""

df.head()

df.shape

df.columns

"""# 2. Data Preprocessing

●	Handle missing values (if any)

●	Encode categorical variables (e.g., Gender)

●	Select relevant features (Age, EstimatedSalary)

●	Separate features (X) and target (y)
"""

df.info()

df.isnull().sum()

"""There are no null values present

### Encode Categorical Variables

The 'Gender' column is a categorical variable with two unique values ('Male', 'Female'). To use this in machine learning models, we need to convert it into a numerical format. We will encode 'Male' as `0` and 'Female' as `1`.
"""

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['Gender'] = le.fit_transform(df['Gender'])
display(df.head())

"""### Separate Features and Target Variable

We will define our features (`X`) as 'Age' and 'EstimatedSalary', and our target variable (`y`) as 'Purchased'.
"""

X = df[['Age', 'EstimatedSalary']]
y = df['Purchased']

print("Features (X) shape:", X.shape)
print("Target (y) shape:", y.shape)

"""#3. Train-Test Split
●	Split dataset into training and testing sets (80/20)

"""

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

"""### Feature Scaling

We will apply Standard Scaling to our features to standardize them. This is often necessary for algorithms that are sensitive to the scale of input features, such as those that use distance calculations (e.g., K-Nearest Neighbors, Support Vector Machines) or gradient descent (e.g., Logistic Regression).
"""

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print("X_train_scaled shape:", X_train_scaled.shape)
print("X_test_scaled shape:", X_test_scaled.shape)

print("\nFirst 5 rows of X_train_scaled:")
display(pd.DataFrame(X_train_scaled, columns=X_train.columns).head())

"""#Model Training (Logistic Regression)

●	Train Logistic Regression model

●	Fit model on training data
"""

from sklearn.linear_model import LogisticRegression

model = LogisticRegression(random_state=42)

model.fit(X_train_scaled, y_train)

"""#Part B — Stretch Problem

1. Model Evaluation

●	Predict on test data

●	Compute:

    ○	Accuracy

    ○	Confusion Matrix

"""

from sklearn.metrics import accuracy_score, confusion_matrix

y_pred = model.predict(X_test_scaled)

accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.4f}")

conf_matrix = confusion_matrix(y_test, y_pred)
print("\nConfusion Matrix:")
print(conf_matrix)

"""### Classification Results Interpretation

*   **Accuracy: 0.8625 (86.25%)**
    This indicates that 86.25% of the model's predictions on the test set were correct.

*   **Confusion Matrix:**
    ```
    [[50  2]
     [ 9 19]]
    ```
    Let's break down these numbers:
    *   **True Negatives (TN): 50**
        The model correctly identified 50 instances where the person did *not* purchase an SUV.
    *   **False Positives (FP): 2**
        The model incorrectly predicted 2 instances where a person *would* purchase an SUV, but they actually did *not*. (Type I error)
    *   **False Negatives (FN): 9**
        The model incorrectly predicted 9 instances where a person would *not* purchase an SUV, but they actually *did*. (Type II error)
    *   **True Positives (TP): 19**
        The model correctly identified 19 instances where the person *did* purchase an SUV.

This analysis shows that the model performs well in identifying those who did not purchase an SUV. However, it has a higher tendency to miss actual purchases (False Negatives) than to incorrectly predict purchases (False Positives).

#2. Visualization

●	Plot decision boundary (optional, 2D features)

●	Interpret classification results
"""

import numpy as np
import matplotlib.pyplot as plt

# Using the scaled test data for visualization
X_plot, y_plot = X_test_scaled, y_test

# Create a meshgrid to plot the decision boundary
x_min, x_max = X_plot[:, 0].min() - 1, X_plot[:, 0].max() + 1
y_min, y_max = X_plot[:, 1].min() - 1, X_plot[:, 1].max() + 1
xx, yy = np.meshgrid(np.arange(x_min, x_max, 0.01),
                     np.arange(y_min, y_max, 0.01))

# Predict for each point in the meshgrid
Z = model.predict(np.c_[xx.ravel(), yy.ravel()])
Z = Z.reshape(xx.shape)

# Plot the decision boundary
plt.contourf(xx, yy, Z, alpha=0.4, cmap=plt.cm.RdYlGn)

# Plot the actual test set data points
plt.scatter(X_plot[:, 0], X_plot[:, 1], c=y_plot, cmap=plt.cm.RdYlGn, edgecolor='k', s=20)

plt.title('Logistic Regression Decision Boundary')
plt.xlabel('Age (Scaled)')
plt.ylabel('Estimated Salary (Scaled)')
plt.show()

"""# 3. Improvement
## Experimenting with Different Test Sizes

### Test Size: 30% (70/30 Split)
"""

# 70/30 Split
X_train_30, X_test_30, y_train_30, y_test_30 = train_test_split(X, y, test_size=0.3, random_state=42)

scaler_30 = StandardScaler()
X_train_scaled_30 = scaler_30.fit_transform(X_train_30)
X_test_scaled_30 = scaler_30.transform(X_test_30)

model_30 = LogisticRegression(random_state=42)
model_30.fit(X_train_scaled_30, y_train_30)

y_pred_30 = model_30.predict(X_test_scaled_30)
accuracy_30 = accuracy_score(y_test_30, y_pred_30)
print(f"Accuracy with 70/30 split: {accuracy_30:.4f}")

"""### Test Size: 25% (75/25 Split)"""

# 75/25 Split
X_train_25, X_test_25, y_train_25, y_test_25 = train_test_split(X, y, test_size=0.25, random_state=42)

# Scale features
scaler_25 = StandardScaler()
X_train_scaled_25 = scaler_25.fit_transform(X_train_25)
X_test_scaled_25 = scaler_25.transform(X_test_25)

# Train model
model_25 = LogisticRegression(random_state=42)
model_25.fit(X_train_scaled_25, y_train_25)

# Predict and evaluate
y_pred_25 = model_25.predict(X_test_scaled_25)
accuracy_25 = accuracy_score(y_test_25, y_pred_25)
print(f"Accuracy with 75/25 split: {accuracy_25:.4f}")

"""### Comparison of Accuracies

*   **Original (80/20 split):** 0.86
*   **70/30 split:** 0.85
*   **75/25 split:** 0.88

## Q1 — What is Logistic Regression? Is it classification or regression?

Logistic Regression is a statistical model primarily used for **binary classification** tasks, meaning it predicts the probability of a categorical dependent variable.

Logistic regression is called a "regression" because it models the relationship between input features and the log-odds of a categorical outcome, using a continuous linear function similar to linear regression

It works by using a **logistic (sigmoid) function** to squash the output of a linear equation into a probability value between 0 and 1. This probability is then mapped to a class label (e.g., 0 or 1) based on a threshold.

### The Logistic (Sigmoid) Function

The core of logistic regression is the sigmoid function, which has an 'S'-shaped curve. It transforms any real-valued number into a value between 0 and 1. The formula is:

$$ \sigma(z) = \frac{1}{1 + e^{-z}} $$

Where:
*   $ \sigma(z) $ is the output (probability between 0 and 1)
*   $ e $ is the base of the natural logarithm
*   $ z $ is the input to the function, which is a linear combination of features:
    z = beta_0 + beta_1 * x_1 + beta_2 * x_2 + .... + beta_n*x_n + e

    

In the context of logistic regression, $ z $ is the linear combination of the input features (e.g., Age, EstimatedSalary) and their corresponding weights (coefficients). The sigmoid function then converts this linear output into a probability of the positive class.

## Q2 (Coding) — Perform train-test split and scaling

## Q3 — What is a confusion matrix? What does it represent?

A **confusion matrix** is a table that is often used to describe the performance of a classification model on a set of test data for which the true values are known. It allows for the visualization of the performance of an algorithm. Each row of the matrix represents the instances in an actual class while each column represents the instances in a predicted class, or vice versa.

It helps us understand the types of errors our model is making, not just how many errors in total.

### Components of a Confusion Matrix:

For a binary classification problem (like our SUV purchase prediction), a confusion matrix typically has four components:

*   **True Positives (TP):** Instances where the model correctly predicted the positive class (e.g., correctly predicted a customer *would* purchase an SUV).
*   **True Negatives (TN):** Instances where the model correctly predicted the negative class (e.g., correctly predicted a customer *would not* purchase an SUV).
*   **False Positives (FP):** Instances where the model incorrectly predicted the positive class when it was actually negative (e.g., incorrectly predicted a customer *would* purchase an SUV, but they *did not*). This is also known as a **Type I error**.
*   **False Negatives (FN):** Instances where the model incorrectly predicted the negative class when it was actually positive (e.g., incorrectly predicted a customer *would not* purchase an SUV, but they *did*). This is also known as a **Type II error**.

### What it Represents:

By looking at these four values, you can calculate various important metrics beyond just accuracy, such as:

*   **Accuracy:** $(TP + TN) / (TP + TN + FP + FN)$
*   **Precision (Positive Predictive Value):** $TP / (TP + FP)$ (Out of all positive predictions, how many were correct?)
*   **Recall (Sensitivity, True Positive Rate):** $TP / (TP + FN)$ (Out of all actual positive cases, how many were correctly identified?)
*   **Specificity (True Negative Rate):** $TN / (TN + FP)$ (Out of all actual negative cases, how many were correctly identified?)
*   **F1-Score:** The harmonic mean of Precision and Recall.

In our previous model evaluation, the confusion matrix `[[50 2] [9 19]]` meant:

*   **TN = 50:** 50 customers were correctly predicted not to purchase.
*   **FP = 2:** 2 customers were incorrectly predicted to purchase (Type I error).
*   **FN = 9:** 9 customers were incorrectly predicted not to purchase (Type II error).
*   **TP = 19:** 19 customers were correctly predicted to purchase.

#Q3 — What is a confusion matrix? What does it represent?

Already performed in the steps above
"""

